### ISSUE TITLE
Breaking change on `v1.4.2`: doesn't replace an alias ended by `/` anymore [minor bug]

### ISSUE THREAD

**Issue by pp0rtal** [justkey007/tsc-alias#102]
<details>
<summary>Thank you for working on tsc-alias :hugs: </summary>

I'm glad to see this project moving, and see a nice peak on npm download!
It's so much more cleaner to drop aliases at compile time!
</details>

### Breaking change description
For this alias config:
```json
        "paths": {
            // I'm doing so to use alias directly + match * file inside
            "@backend/config": ["config"],
            "@backend/config/*": ["config/*"],
        }
```

Using it like following:
```typescript
import config from "@backend/config/";
```

Then, my import is **not** converted

```typescript
const config_1 = require("@backend/config");
```

### History
I bumped my tsc-watch from `1.3.7` to `1.6.4` and discovered the bug.
I wanted to find why it broke:

```
// Finding breaking change in tagged versions
1.4.1: OK! :)
1.4.2: BROKEN!

// Finding breaking in commits
e980fee75851012c52878c0d23c2dc05fe83bce4: (1.4.1): OK
18b252a5de960b813490ce6fa6e3a447b943d61e: OK
563183822a006e5f5e51c0a9125fd3f77c18f1ee: BROKEN

... note it's broken to current version 1.6.4
```

So it seems that this minor change actually broke something https://github.com/justkey007/tsc-alias/commit/563183822a006e5f5e51c0a9125fd3f77c18f1ee
I didn't dived too much, but it seems the `isAlias` boolean is `false` instead of `true` so the alias is simply not spotted at all 
https://github.com/justkey007/tsc-alias/blob/563183822a006e5f5e51c0a9125fd3f77c18f1ee/src/index.ts#L186

https://github.com/justkey007/tsc-alias/blob/563183822a006e5f5e51c0a9125fd3f77c18f1ee/src/index.ts#L189-L190

And actually in this case I'm `requiredModule === alias.prefix` but honestly I don't have enough knowledge to say what's wrong

### Is it a bug?
I would say yes :thinking: 
- for instance `@backend/config/prod/` (folder) is well recognized
- but `@backend/config/` is not but it's still a folder.

That's a superfluous `/` so I can just refresh my codebase where the bug occurs obviously.
Or maybe this way of using `@alias` + `@alias/*` is wrong do you know how I can improve?

**Comment by raouldeheer** [comment]
@pp0rtal 
Try using `@backend/config` instead of `@backend/config/`. Does that work or is that also broken?
