### ISSUE TITLE
Breaking change on `v1.4.2`: replacement for non-alias :exploding_head: 

### ISSUE THREAD

**Issue by pp0rtal** [justkey007/tsc-alias#103]
Hi!
I've got a second bug spotted on ([first minor here](https://github.com/justkey007/tsc-alias/issues/102)), and since 1.4.2 
and I think this one is quite interesting as it's **replacing a NodeJs native library** import statement.

### Description / steps to reproduce
1. `tsconfig.json` alias config doesn't matter!
```json
"path": {} // empty
```

2. file to convert `/utils/index.js`, which does contain a Node.js native package
_(for instance [cluster](https://nodejs.org/api/cluster.html), but it works for a `child_process`, `fs` or whatever)_
```typescript
const cluster = require("cluster");
```

3. And, I've got some file `/cluster.js`:
```javascript
// the bug occurs as long the file "cluster" exists
```

The `/utils/index.js` will be rewritten as following :exploding_head: :exploding_head: :exploding_head: 
```javascript
const cluster = require("../cluster");
```

### Origin
That's not the same source as the minor bug I've spot!
This issue is coming from this commit: https://github.com/justkey007/tsc-alias/commit/18b252a5de960b813490ce6fa6e3a447b943d61e

```
// Finding breaking change in tagged versions
1.4.1: OK! :)
1.4.2: BROKEN!

// Finding breaking in commits
e980fee75851012c52878c0d23c2dc05fe83bce4: (1.4.1): OK
18b252a5de960b813490ce6fa6e3a447b943d61e: BROKEN

... note it's broken to current version 1.6.4
```

I'm trying to spot exactly which code did this regression, probably `replaceBaseUrlImport` but I'm not sure to be able to edit this code without breaking things :disappointed: 

Let me know if I can help

**Comment by raouldeheer** [comment]
Try this config: https://github.com/justkey007/tsc-alias/issues/79#issuecomment-994896616

**Comment by pp0rtal** [comment]
@raouldeheer Thanks for your quick answer!

I tried to add `tsc-alias` config in my `tsconfig.json` as following 
```javascript
{
    "compilerOptions": {
        "baseUrl": ".",  // If I understand this is the problem source, and yes my project files are in root fs :/
         ...
    },
    ....
    "ts-node": {}, // I've got some ts-node config working for instance
    "tsc-alias": {
        "replacers": {
            "BaseUrl": {
                "enabled": false
            }
        }
    }
```

But I still have the same issue

**Comment by raouldeheer** [comment]
The name of BaseUrl has been changed to 'baseurl' all lowercase.

**Comment by justkey007** [comment]
@pp0rtal please replace `BaseUrl` with `base-url`.

**Comment by pp0rtal** [comment]
@raouldeheer cc @justkey007 Works perfectly know! :smile: 
And I see you fixed the original solution perfect :+1: 
I'm closing ticket then.

----

Just by curiosity
I'm surprised this behavior is the default, what is the use-case of this?
Shouldn't be `base-url` default to false, and activated for edge cases?

**Comment by raouldeheer** [comment]
"All module imports with non-relative names are assumed to be relative to the [baseUrl](https://www.typescriptlang.org/tsconfig#baseUrl)." -[typescript handbook](https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url)
