### ISSUE TITLE
Unable to detect files when the project includes files in a parent directory

### ISSUE THREAD

**Issue by MergeCommits** [justkey007/tsc-alias#107]
I have a setup where there's a `functions` directory that contains a project, and then a `shared` folder adjacent to it with additional TS files.

When I add the paths for the files in the `shared` folder to the project and include those files, the alias command no longer detects any files until I rerun the build with the shared path removed.

### Reproduction
https://github.com/MergeCommits/tsc-alias-attempt

- Run the build command.
- Run the alias command
- The verbose log shows that it finds no files.
- Remove any reference to the shared path in `index.ts`.
- Rerun the build and alias commands.
- It now detects and converts the files properly.

**Comment by raouldeheer** [comment]
@MergeCommits Are you running on linux or windows?
The reproduction is very similar to project1 in the testing projects. It seems that project1 doesn't resolve aliases on windows but works on linux.

**Comment by MergeCommits** [comment]
I'm running on Windows.

**Comment by raouldeheer** [comment]
Found the bug in `getProjectDirPathInOutDir`, globbysync needs outDir to be in posix format.

**Comment by raouldeheer** [comment]
Thank you @MergeCommits for reporting this bug, it should be fixed in #108 
The reproduction repo was very helpful.
