### ISSUE TITLE
tsc-alias replaces path that shouldn't be replaced

### ISSUE THREAD

**Issue by snoweuph** [justkey007/tsc-alias#109]
Node Version: 16.14.2
tsc-alias Version: ^1.6.5
tsc Version: 4.5.5

I have a file structure of
```
src│
└───base
│   │   StateManager.ts
│   │   ...
│   
└───events
      |    ...
```

In My tsconfig.json I defined some paths like, there is none called 'events'
```json
"paths": {
            "@base/*": [
                "src/base/*"
            ]
        }
```
and I defined the baseUrl
```json
"baseUrl": "."
```

inside of the `StateManager.ts` I import the EventEmitter from the default package called 'events'
```ts
import { EventEmitter } from 'events';
```

**PROBLEM:**
adding the `baseUrl` inside of the `tsconfig.json` lets `tsc-alias` think that the import of EventEmitter from 'events' is meant to be a import of the folder named 'events'. removing the `baseUrl` from the `tsconfig.json` or just only running `tsc` without running `tsc-alias` after it "fixes" the problem, but I need to use `tsc-alias` because I needed to remove my relative imports because they got quite long, same thing is the reason why I need to set the `baseUrl`.

**QUESTION:**
Is there something I can do in the configuration to fix this problem with tsc-alias or could I set the `removeComments` flag in the `tsconfig.json` to false and add some type of comment that will tell tsc-aliases to do the right thing?

- [x] Tryed To think
- [x] Added Version Information
- [x] Told the "exact" Problem  
- [x] been patient and waited for the reply
- [x] got reply
- [x] got some kind of fix

**Comment by raouldeheer** [comment]
Try this config: https://github.com/justkey007/tsc-alias/issues/79#issuecomment-994896616

Duplicate of #103

**Comment by snoweuph** [comment]
thx, that helped, sry for not checking the closed issues and stealing your time

**Comment by raouldeheer** [comment]
No problem, I'll make a frequently asked questions list soon.

**Comment by snoweuph** [comment]
:+1:
