### ISSUE TITLE
Fail to read compilerOptions.outDir

### ISSUE THREAD

**Issue by phuctm97** [justkey007/tsc-alias#11]
This bug is found on `v1.2.1`, not `v1.2.0`: 

I got an incorrect error saying: `compilerOptions.outDir is not set`.

My tsconfig:

```json
{
  "extends": "@tsconfig/node12/tsconfig.json",
  "compilerOptions": {
    "outDir": "js",
    "baseUrl": ".",
    "paths": { "~/*": ["./*"] }
  },
  "exclude": ["node_modules", ".next"],
  "include": [
    "next-env.d.ts",
    "lib/**/*.ts",
    "utils/**/*.ts",
    "scripts/**/*.ts"
  ]
}

```

Seems like the new `loadConfig` API is working incorrectly.

**Comment by justkey007** [comment]
Hello, I just tried again with your tsconfig and didn't get this error. Can you provide me with an example of reproducing this error using a repository. Thank you
