### ISSUE TITLE
Using `resolveFullPaths` with watch mode cause the transpiled file not to have `.js` extenstion

### ISSUE THREAD

**Issue by slier81** [justkey007/tsc-alias#117]
As title,
When using `resolveFullPaths` in watch mode, the transpiled file doesnt have `.js` extension
It work just fine without watch mode

tsconfig.json

```
{
	"compilerOptions": {
             ....
	},
	"tsc-alias": {
		"verbose": false,
		"resolveFullPaths": true,
	}
}
```

And run `tsc -w & tsc-alias -w` causing the transpiled file lost its extension

**Comment by slier81** [comment]
@raouldeheer Running `tsc && tsc-alias -r debugger.js`  give me:

`tsc-alias error: Failed to import replacer "debugger.js"`

**Comment by tkcto** [comment]
@raouldeheer so whats the update on this?

**Comment by raouldeheer** [comment]
@tkcto I haven't been able to reproduce this bug. That makes it exceedingly difficult to give a time estimate.

**Comment by slier81** [comment]
@raouldeheer ah ic.. to add some context, when using `w` flag, `tsc-alias` no longer translate path alias ( and does not add `.js` extension )

**Comment by slier81** [comment]
@raouldeheer i have setup demo repo for you with reproducible bug https://github.com/slier81/tscalias-bug-demo

**Comment by slier81** [comment]
@raouldeheer 

> @slier81 I've tried running the `dev:compile` script, but it doesn't seem to start tsc-alias. Changed the `dev:compile` script from:
> 
> ```shell
> tsc -w & tsc-alias -w
> ```
> 
> To:
> 
> ```shell
> concurrently \"tsc -w\" \"tsc-alias -w\"
> ```
> 
> After doing that it worked and replaced aliases.
> 
> Can you try this? This could fix the issue.
> 
> Replacing the `dev:compile` script to this would also solve the issue.
> 
> ```json
> "dev:tsc": "tsc -w",
> "dev:tsc-alias": "tsc-alias -w",
> ```
Yes this  fix the issue.. But the second solution apparently only work, if there is already generated output.
But according to your documentation `"build:watch": "tsc -w & tsc-alias -w"` should work.. 
Why running `tsc -w & tsc-alias -w` dont work? Maybe you need to update your documentation? thx anyway for the fix.. Greatly appreacited

**Comment by slier81** [comment]
I have to mention this, actually solution number 1 `concurrently \"tsc -w\" \"tsc-alias -w\"` , actually also not working if this is the first time you running this command ( meaning, there is not generated output yet ).. On subsequent running of this command, it will work.. Quick fix would be `tsc && (concurrently \"tsc -w\" \"tsc-alias -w\")`

**Comment by oleksandr-danylchenko** [comment]
@nmsobri 
Unfortunately, it `tsc && (concurrently \"tsc -w\" \"tsc-alias -w\")` doesn't help either. After you do any change in the source files, the aliases are getting back

---

@raouldeheer do you have any thoughts on it?

**Comment by oleksandr-danylchenko** [comment]
@nmsobri 
Thank you! I faced the same exact problem and the `tsc && (concurrently \"tsc -w\" \"tsc-alias -w\")` helped!

@raouldeheer, could you please put in the docs? Because it's pretty confusing on the first interaction with the library to not be able to work with it in the watch mode :sweat_smile:
