### ISSUE TITLE
transpilation to js breaks when file name is same as library

### ISSUE THREAD

**Issue by titus-ong** [justkey007/tsc-alias#120]
## Expected behaviour

tsc-alias should not affect tsc transpilation. 

## Current behaviour

tsc-alias causes tsc to transpile library imports as local module imports when they share the same name.

## Possible solution

Unfortunately, I have not read through tsc-alias' code yet, but a workaround for others facing the same issue is to simply rename their files.

## Steps to reproduce

I'm using mongoose as an example.

```typescript
// mongoose.ts
import mongoose from "mongoose";

mongoose.connect('mongodb://localhost:27017/myapp');
```
```typescript
// transpiled mongoose.js
const mongoose_1 = __importDefault(require("./mongoose")); // should be require("mongoose")
```
My package.json:
```json
{
  "scripts": {
    "compile": "shx rm -rf lib/ && tsc && tsc-alias"
  }
}
```
My tsconfig.json:
```json
{
  "compilerOptions": {
    "lib": ["esnext.bigint"],
    "target": "es2018",
    "module": "commonjs",
    "outDir": "./lib",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "paths": {
      "@something": ["./src/something"]
    },
    "baseUrl": "."
  }
}
```

## Context
tsc-alias version: 1.6.7
typescript version: 4.3.5

**Comment by raouldeheer** [comment]
https://github.com/justkey007/tsc-alias/discussions/110 Replaces path that shouldn't be replaced

**Comment by titus-ong** [comment]
> #110 Replaces path that shouldn't be replaced

Hm interesting, wasn't aware enabling paths would have such an effect. The fix on your FAQ works, thanks.
