### ISSUE TITLE
Not working on workspaces with yarn v1

### ISSUE THREAD

**Issue by hiukky** [justkey007/tsc-alias#127]
Do we have any usage notes regarding yarn workspaces? I'm getting the message of `tsc-alias error: File undefined not found`, can't resolve the configuration from a link.

I still looked at details, but using previously with simple packages it was working, but with custom scope "@foo/*" the configuration is not resolved.

I tested `tsc --showConfig` and the configuration is being loaded correctly by tsc, so I can assume that something in the tsc-alias configuration resolution seems to not follow symlinks or something.

**Comment by raouldeheer** [comment]
@hiukky What does your tsconfig look like? And where are the files that it extends?

**Comment by raouldeheer** [comment]
tsc-alias doesn't support aliases in tsconfig. Try using `../../presets/tsconfig`

**Comment by hiukky** [comment]
actually it supports it, only it needs to point directly to the file, this type of import is also not pleasant lol

**Comment by hiukky** [comment]
https://github.com/justkey007/tsc-alias/blob/master/src/helpers/config.ts#L159-L186

I think here you need to consider one more condition!

**Comment by hiukky** [comment]
I think this may be unnecessary!

```tsk
[
   '/home/hiukky/.tmp/ts-solution-builder/packages/bar/node_modules/@presets/tsconfig',
   '/home/hiukky/.tmp/ts-solution-builder/node_modules/@presets/tsconfig',
   '/home/hiukky/.tmp/node_modules/@presets/tsconfig'
]
```

Because when tsconfig extends a configuration it only resolves if it is valid, otherwise the compiler shows an error!

If tsc fails, tsc-alias should not be invoked!

another thing is that if a tsconfig or tsconfig.json is implicitly pointed to in the inheritance, tsconfig assumes a tsconfig.json by default.

what do you think @justkey007

**Comment by raouldeheer** [comment]
Because when the path ends with `.json` it checks for the file, if that is not found the program will continue with next item in the list. Because of this everything after line 173 is already in an else branch in the program code.

**Comment by raouldeheer** [comment]
@hiukky would #128 fix this issue?

**Comment by hiukky** [comment]
![image](https://user-images.githubusercontent.com/26740246/174316590-fe2cde12-f9af-4b50-bd91-5fbcbb06fed7.png)
Well I understand, but this is really a problem! what is the difference from the local module I am using in the workspace `@presets/tsconfig` to https://github.com/sindresorhus/tsconfig (it works) ?

The only difference I see is a module installed directly in the npm registry and another one linked internally by yarn! 

And I'm only assuming this with yarn, I haven't tested with npm and pnpm workspaces but if they both share the modules by links, chances are you'll have the same problem using them!

Translated with www.DeepL.com/Translator (free version)

**Comment by hiukky** [comment]
@raouldeheer Yes #128 solves it! ;/
