### ISSUE TITLE
`import '.'` improperly mapped.

### ISSUE THREAD

**Issue by KyleSmith0905** [justkey007/tsc-alias#137]
### Before:
`import { something } from '.';`

### After:
`import { something } from 'index.js';`

### Something it could be transformed to:
`import { something } from './index.js';`

## Explanation
You probably know why. But `index.js` refers to the root, `.` and `index.js` refers to an `index` file at the same level as the file. If anyone has this error, you could change the imports from `.` to `./index`.

**Comment by raouldeheer** [comment]
@KyleSmith0905 can you provide us the console output when running with --debug? Working version and nonworking version?

**Comment by KyleSmith0905** [comment]
I don't have a separate environment to test this on, so I'll be minimizing the log output to relevant stuff. If I should include more, like version number (1.7.0), tell me.

Working Version using `./index.js`:
```
tsc-alias debug: Found files: [
  '<file path>',
]
tsc-alias debug: Starting to replace file: '<file path>'
tsc-alias debug: default replacer - requiredModule:  './index.js'
tsc-alias debug: default replacer - alias:
tsc-alias debug: base-url replacer - requiredModule:  './index.js'
tsc-alias debug: base-url replacer - already resolved
```

Not working version using `.`
```
tsc-alias debug: Found files: [
  '<file path>',
]
tsc-alias debug: Starting to replace file: '<file path>'
tsc-alias debug: default replacer - requiredModule:  '.'
tsc-alias debug: default replacer - alias:
tsc-alias debug: base-url replacer - requiredModule:  '.'
tsc-alias debug: base-url replacer - already resolved
```

**Comment by raouldeheer** [comment]
@KyleSmith0905 can you check if you are running with -f? And what does the debugger return in the first part until the aliastrie?

**Comment by raouldeheer** [comment]
@KyleSmith0905 I have found the bug that was causing the issue, pr following soon. A workaround for this issue is to replace `.` with `./`.
