### ISSUE TITLE
Getting extra "../" added to the resolved path

### ISSUE THREAD

**Issue by ArtursTimofejevs** [justkey007/tsc-alias#146]
Hello!

Hope everyone is doing well.

Been trying to setup `tsc-alias` to work for us when we develop packages. We have a single mono repository. In that mono repository we have packages that are shared between apps and packages. I'm building a little watch tool that will build declaration files only so we have that sweet type support between packages while developing. Everything seems fine until I realised that you also need to resolve the paths and I stumbled upon this little tool.

But...

It looks like it's adding extra `../` to some of the files for some reason?

Heres the scripts being run:

`pnpm tsc --declaration --emitDeclarationOnly --declarationDir "./dist/types"`

and then 

`pnpm tsc-alias`

The result is the following:

![image](https://user-images.githubusercontent.com/87968958/203096930-a9e972e9-8762-490e-8b70-7de861c76eab.png)

It only happens on 5 of the 10 modules that use this alias, any idea what I have done wrong?

`tsconfig` for reference

```json
{
	"compilerOptions": {
		"target": "ESNext",
		"strictNullChecks": true,
		"useDefineForClassFields": true,
		"lib": ["DOM", "DOM.Iterable", "ESNext"],
		"allowJs": false,
		"skipLibCheck": false,
		"esModuleInterop": true,
		"allowSyntheticDefaultImports": true,
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"module": "ESNext",
		"moduleResolution": "Node",
		"resolveJsonModule": true,
		"isolatedModules": true,
		"jsxImportSource": "@emotion/react",
		"jsx": "react-jsx",
		"baseUrl": "src",
		"paths": {
			"@": ["./lib"]
		},
		"outDir": "dist"
	},
	"include": ["./src/lib/**/*"],
	"references": [{ "path": "./tsconfig.node.json" }],
	"tsc-alias": {
		"replacers": {
			"base-url": {
				"enabled": true
			}
		}
	}
}
```

**Comment by raouldeheer** [comment]
@ArtursTimofejevs can you provide us the console output when running with --debug?  Could you try changing the declarationDir to types instead of dist/types? Maybe it's resolving the imported files to the js.

**Comment by ArtursTimofejevs** [comment]
@raouldeheer 

https://gist.github.com/ArtursTimofejevs/e51cafe95a20b38e28ee4e8735380f58

For the debug,

Changing the directory did not do anything unfortunately, i'll keep digging.

**Comment by raouldeheer** [comment]
@ArtursTimofejevs Could you try running tsc-alias with `--dir dist/types`?

**Comment by ArtursTimofejevs** [comment]
That did the trick! Not sure if its a bug or not so feel free to close :) Thank you!! Happy tuesday :)
