### ISSUE TITLE
Replacing package names with folders incorrectly

### ISSUE THREAD

**Issue by netroy** [justkey007/tsc-alias#152]
`tsc-alias` is incorrectly replacing package names like `events`, `axios`, etc if a folder with that name exists in the src folder.

I've managed to isolate the issue into [this repo](https://github.com/netroy/tsc-alias-bug).
If you run `npm run build` and then look at `dist/index.js`, the imports look incorrect.

![Source](https://user-images.githubusercontent.com/196144/210460520-abd5c571-af21-4282-af08-bd76e575f275.png)

![Compiled](https://user-images.githubusercontent.com/196144/210460436-ae3f6cad-f768-4783-9220-6e4d51ea3e25.png)

PS: This does not happen if I change `include` in `tsconfig` from `src/**/*.ts` to `src/index.ts`, but then only that one file compiles.

**Comment by raouldeheer** [comment]
@netroy this is probably FAQ (#110) question 1

**Comment by netroy** [comment]
@raouldeheer that does fix the issue for me. Should have looked at the FAQ first.
Thanks a lot ❤️
