### ISSUE TITLE
Does not resolve dynamic import path

### ISSUE THREAD

**Issue by Edouard127** [justkey007/tsc-alias#156]
I tried to import a module dynamically with my directory alias as such

```ts
[...]
const imp = (await import("@/client/interactions/" + file)).default(db, ctx) as CommandInteractionHandler
[...]
```
And it resulted with the following error:
`Error: Cannot find module '@/client/events/guildCreate.js'`

Here is my build command:
```
"scripts": {
    "build": "tsc && tsc-alias",
  },
  ```
  
  I'm using the latest release of tsc-alias

**Comment by raouldeheer** [comment]
Tsc-alias wil try to resolve to filepath. But because the filepath is not complete it won't find the find and thus not replace the alias.
This problem could be solved by using a custom replacer.

**Comment by Edouard127** [comment]
> Tsc-alias wil try to resolve to filepath. But because the filepath is not complete it won't find the find and thus not replace the alias. This problem could be solved by using a custom replacer.

Can't it just replace the @ ?

**Comment by andersekdahl** [comment]
It doesn't seem to work on any `import()` regardless of if it contains a variable like for OP or if it's a static path used for lazy loading.
