### ISSUE TITLE
Adding `../` before external dependency from node_modules

### ISSUE THREAD

**Issue by giva9712** [justkey007/tsc-alias#193]
# Before compiling
![image](https://github.com/justkey007/tsc-alias/assets/40331144/05dc1f63-e593-43a7-a71a-3f1f11104e27)
# After compiling
![Screenshot 2023-08-24 at 23 58 47](https://github.com/justkey007/tsc-alias/assets/40331144/35b8a552-5d1b-4df2-b8d9-26a8213b2666)
![image](https://github.com/justkey007/tsc-alias/assets/40331144/7835195d-4bd7-4783-9ca3-a6632f05a2a2)

# To produce
`graphql` is external dependency I installed from npm registry and I have `~/graphql` path alias which points to `./src/graphql` so that I think it collides with `~/graphql`
![image](https://github.com/justkey007/tsc-alias/assets/40331144/7562ceb1-1e10-4e68-8e9d-f2ce54b5637f)
## tsconfig.json
![image](https://github.com/justkey007/tsc-alias/assets/40331144/875d4c47-b8e0-4239-a186-306321d1ae03)

**Comment by kyle-belle** [comment]
I get the same issue. In my case it happen when i try to import dayjs

relavant `tsconfig.json`
```json
"outDir": "./build",
      "paths": {
        "@app/db": ["./db", "../db"],
        "@app/db/*": ["./db/*", "../db/*"],
        "@app/redis": ["./redis", "../redis"],
        "@app/redis/*": ["./redis/*", "../redis/*"],
        "@app/emitter": ["./emitter", "../emitter"],
        "@app/emitter/*": ["./emitter/*", "../emitter/*"],
        "@app/dayjs": ["./dayjs", "../dayjs"],
        "@app/dayjs/*": ["./dayjs/*", "../dayjs/*"],
        "@app/utils": ["./utils", "../utils"],
        "@app/utils/*": ["./utils", "../utils"],
        "@app/values": ["./values", "../values"],
        "@app/values/*": ["./values/*", "../values/*"]
      },
```
tsc input:
```typescript
import dayjs from "dayjs";
```
tsc output/tsc-alias input:
```javascript
const dayjs_1 = __importDefault(require("dayjs"));
```
tsc-alias output:
```javascript
const dayjs_1 = __importDefault(require("../dayjs"));
```

whats strange is there are other dayjs imports that weren't touched
```javascript
const dayjs_1 = __importDefault(require("../dayjs"));
const advancedFormat_1 = __importDefault(require("dayjs/plugin/advancedFormat"));
const arraySupport_1 = __importDefault(require("dayjs/plugin/arraySupport"));
const isLeapYear_1 = __importDefault(require("dayjs/plugin/isLeapYear"));
```

**Comment by kyle-belle** [comment]
its really unfortunate because this is the closest i got to having my project transpiled and running with just node. literally if i just remove the `../` from this line manually it works. The other alternative have even more issues. `typescript-transform-paths` doesn't correctly replace relative paths for me.

this package correctly replaces
```javascript
require("@app/redis")
```
with
```javascript
require("../redis")
```
 it treated `outDir` as the new base/root which is what i actually want

 `typescript-transform-paths` does this (still tries to pull original ts file from outside `outDir`):
 ```javascript
require("../../../redis");
```

**Comment by fdendorfer** [comment]
This solved it for me: https://github.com/justkey007/tsc-alias/issues/185
