### ISSUE TITLE
tsc-alias incorrectly adds .js extension to a module from node_modules

### ISSUE THREAD

**Issue by olalonde** [justkey007/tsc-alias#197]
I have a file  `stripe.ts` which imports the `stripe` module (npm install stripe). tsc-alias adds a .js extension to it for some reason.

```
// stripe.ts
import Stripe from "stripe"
```

becomes

```
// stripe.js
import Stripe from "stripe.js";
```

**Comment by olalonde** [comment]
Fixed with this:

```typescript
{
  "compilerOptions": {
   // ...
  },
  "tsc-alias": {
    "debug": true,
    "verbose": true,
    "replacers": {
      "base-url": {
        "enabled": false
      }
    }
  }
}
```

**Comment by olalonde** [comment]
Reopening because that configuration broke some other stuff. I believe this is a bug. 

if the module specifier is not a file path, tsc-alias shouldn't add a `.js` extension even if there is a file with that name.

**Comment by olalonde** [comment]
Ended up writing this: https://github.com/olalonde/tsc-module-loader

**Comment by U-4-E-A** [comment]
Was this by any chance where you had a file with the same name as something you were importing? In my case I had a file called react.ts of react tools with used `import { useEffect, useRef, DependencyList, MutableRefObject, LegacyRef, RefCallback } from 'react'`. tsc-alias is still converting this to `'react.js'`.

**Comment by melalj** [comment]
Having the exact bug.
It's shocking that `tsc` doesn't support the alias with the compiler out of the box.
