### ISSUE TITLE
Alias replacement failed when importing library containing alias

### ISSUE THREAD

**Issue by daividh** [justkey007/tsc-alias#20]
**Issue**

When using libraries starting with a "@" (like `@esfx/collections-hashmap`) using a tsconfig.json containing bellow config make import replacement fail with error `Error: Cannot find module './esfx/collections-hashmap'`

tsconfig.json
```
"baseUrl": "./src",
"paths": {
  "@/*": [
    "./*",
  ],
},
```

**How to reproduce**

Start test on this ### ### [branch](https://github.com/daividh/tsc-alias/tree/alias_issue)

**Comment by justkey007** [comment]
I would like to have the structure of your project to better debug. Thank you

**Comment by transcranial** [comment]
I have the exact same issue after going from `1.2.6` -> `1.2.7`, presumably due to PR https://github.com/justkey007/tsc-alias/pull/19. `@/aliased/path` should be transformed and `@scoped/package` left alone, but now the latter is also being (incorrectly) transformed.

**Comment by justkey007** [comment]
Thank you to all of you. The problem is solved
