### ISSUE TITLE
How to tsc-alias it with mocha?

### ISSUE THREAD

**Issue by Kripu77** [justkey007/tsc-alias#207]
Hi everyone,

I'm currently working on a TypeScript project, and I've been using the tsc-alias package to manage path aliases in my TypeScript codebase. This has worked well for the application code, but I'm facing challenges when trying to set up and run tests using Mocha.

Problem:

I'd like to find a solution or guidance on how to effectively integrate tsc-alias with Mocha for running tests. Specifically, I want to ensure that Mocha recognizes and resolves the TypeScript path aliases correctly during test execution.

Current Configuration:

Here's a snippet of my tsconfig.json:

```
{
  "extends": "ts-node/node16/tsconfig.json",
  "ts-node": {
    // It is faster to skip typechecking.
    // Remove if you want ts-node to do typechecking.
    "transpileOnly": true,
    "files": true,
   
  },
  
 "compilerOptions": {
   "module": "commonjs",
   "esModuleInterop": true,
   "target": "es6",
   "moduleResolution": "node",
   "sourceMap": true,
   "outDir": "dist",
   "rootDir": "src",
   "declaration": true,
   "types": ["node", "mocha"],
   "skipLibCheck": true,
    "paths": {
      "@/*": ["./src/*"]
    }
 },
 "lib": ["es2015"],
 "include": ["src/"],
 "exclude": [
     "dist",
     "node_modules",
     "src/**/*.spec.ts"
   ],
}
```
My test script in package.json

```mocha --experimental-specifier-resolution=node --loader ts-node/esm --require ts-node/register --require dotenv/config --recursive 'test/*.test.ts'"```

I'm seeking advice, examples, or any information on how to configure Mocha to work with tsc-alias for testing. Are there specific steps, plugins, or configurations that I need to add to my Mocha setup?

Thank you!

**Comment by Kripu77** [comment]
Hi Guys, I was able to solve it by using `tsconfig-paths/register` I have my test script updated as:

`"test:unit": "mocha --experimental-specifier-resolution=node  --loader ts-node/esm --require ts-node/register --require tsconfig-paths/register  --require dotenv/config --recursive 'test/*.test.ts'",
`

**Comment by svenjacobs** [comment]
Unfortunately `tsconfig-paths` currently [doesn't work with ESM](https://github.com/dividab/tsconfig-paths/issues/243). Is there a solution for `tsc-alias`?

**Comment by meszaros-lajos-gyorgy** [comment]
Anyone struggling with this try replacing the `ts-node` package with `@hyperse/ts-node`, it automatically resolves paths.
https://github.com/hyperse-io/ts-node

Found out about this repo here: https://github.com/jonaskello/tsconfig-paths/issues/243#issuecomment-3535391034
