### ISSUE TITLE
Nodemon support!

### ISSUE THREAD

**Issue by vimalmistry** [justkey007/tsc-alias#24]
This plugin working fine while compilation.

Can you guide me how to use in watch mode with nodemon/ts-node ?

```bash
node --inspect -r ts-node/register src/server.ts
```

**Comment by justkey007** [comment]
To use with noidemon you just have to compile the typescript project in watch mode (`tsc -w`) and run in another terminal or in the background `tsc-alias -w`. And then you can run nodemon on the input file of the `dist` or` build` folder.

The nodemon command will be as follows:
`nodemon --watch dist --inspect dist/server.js`

I hope that that will be able to help you

**Comment by hk-skit** [comment]
Following works for me:

```
"scripts": {
    "lint": "eslint .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "clean": "sh ./scripts/clean.sh",
    "setup": "sh ./scripts/setup.sh",
    "build": "tsc && tsc-alias",
    "start": "node dist/app.js",
    "watch-ts": "concurrently \"tsc --watch\" \"tsc-alias -w\"",
    "prepare": "husky install",
    "pre-commit": "lint-staged",
    "dev": "npm run build && concurrently \"npm:watch-ts\" \"nodemon dist/app.js\""
  }
```
