### ISSUE TITLE
Feature Request: Disable console messages

### ISSUE THREAD

**Issue by bohdanbirdie** [justkey007/tsc-alias#28]
Hi!
Great work on the library!

Would you mind adding a flag to disable default console.log messages?
To be specific:
https://github.com/justkey007/tsc-alias/blob/master/src/index.ts#L30
https://github.com/justkey007/tsc-alias/blob/master/src/index.ts#L249

Thanks!

**Comment by justkey007** [comment]
Hello, thanks for the appreciation. I would like to know how the console output is giving you trouble and wouldn't it be better to redirect it to `/dev/null` ?

**Comment by bohdanbirdie** [comment]
I'm adding it as a hook for the rollup config
![image](https://user-images.githubusercontent.com/23266928/118479672-fb1d5100-b719-11eb-8ef9-4f250bbf3be8.png)

And it is adding extra messages to the terminal output, which I would like to reduce. (Keeping the error messages of course)
![image](https://user-images.githubusercontent.com/23266928/118479757-15efc580-b71a-11eb-9792-ba891d9bd908.png)

**Comment by justkey007** [comment]
Understood and noted, as soon as I have a little time I will add this functionality or if you can send a pull request that would be good. Thank you
