### ISSUE TITLE
Very slow build times?

### ISSUE THREAD

**Issue by BronzW** [justkey007/tsc-alias#30]
I don't know if it's a problem you are able to solve, but tsc-alias is really screwing up my build times. I run tsc-alias both manually and in watch mode and it takes up about 90% of the build time. It would be really nice if some performance patches would be done, as I think it would boost this package popularity.

**Comment by jjangga0214** [comment]
`replaceAlias` is called against every target files. 

https://github.com/justkey007/tsc-alias/blob/11379a252c80be635e989a69bcedb82bf07823e7/src/index.ts#L264-L269

However, file IO is synchronous(`readFileSync`), instaed of being async. 
https://github.com/justkey007/tsc-alias/blob/11379a252c80be635e989a69bcedb82bf07823e7/src/index.ts#L223-L224

**Comment by jgod** [comment]
Yes. I noticed ESBuild for 15k LOC takes just over a second, and resolving the imports using this package takes 500ms.
