### ISSUE TITLE
Versions 1.3.0 and 1.3.1 are not works for my project.  

### ISSUE THREAD

**Issue by Levhav** [justkey007/tsc-alias#34]
Hi, 
Versions 1.3.0 and 1.3.1 are not works for my project, but version 1.2.11 is working fine.

I have this error on the last version. But when I run `npx tsc-alias@1.2.11` it works without errors.

```
Info: === tsc-alias starting ===
/home/victor/GIT/Nanoheal.com/nh_deployment/packages/cloud-backend/node_modules/tsc-alias/dist/index.js:121
        const isAlias = requiredModule.includes('/')
                                       ^

TypeError: Cannot read property 'includes' of undefined
    at replaceImportStatement (/home/victor/GIT/Nanoheal.com/nh_deployment/packages/cloud-backend/node_modules/tsc-alias/dist/index.js:121:40)
    at /home/victor/GIT/Nanoheal.com/nh_deployment/packages/cloud-backend/node_modules/tsc-alias/dist/index.js:145:83
    at String.replace (<anonymous>)
    at ImportPathResolver.replaceSourceImportPaths (/home/victor/GIT/Nanoheal.com/nh_deployment/packages/cloud-backend/node_modules/tsc-alias/dist/utils/ImportPathResolver.js:23:35)
    at Object.replaceSourceImportPaths (/home/victor/GIT/Nanoheal.com/nh_deployment/packages/cloud-backend/node_modules/tsc-alias/dist/utils/ImportPathResolver.js:64:51)
    at replaceAlias (/home/victor/GIT/Nanoheal.com/nh_deployment/packages/cloud-backend/node_modules/tsc-alias/dist/index.js:145:32)
    at Object.replaceTscAliasPaths (/home/victor/GIT/Nanoheal.com/nh_deployment/packages/cloud-backend/node_modules/tsc-alias/dist/index.js:168:13)
    at Object.<anonymous> (/home/victor/GIT/Nanoheal.com/nh_deployment/packages/cloud-backend/node_modules/tsc-alias/dist/bin/index.js:16:5)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
error Command failed with exit code 1.
```

Thanks for your project!

**Comment by justkey007** [comment]
Hi, I would like to have more details on your project structure or either please add a test project with the same structure and config of your project in order to fail the tests. Thank you

**Comment by mikeahirsch** [comment]
I was getting `Cannot read property 'includes' of undefined` and had to switch to `npx tsc-alias@1.2.11` for it to work as well.

**Comment by justkey007** [comment]
> I was getting `Cannot read property 'includes' of undefined` and had to switch to `npx tsc-alias@1.2.11` for it to work as well.

Hi, I would like to have more details on your project structure or either please add a test project with the same structure and config of your project in order to fail the tests. Thank you

**Comment by kangzeroo** [comment]
I am getting this issue too, but like @mikeahirsch said it works if I switch to `npx tsc-alias@1.2.11`

**Comment by justkey007** [comment]
> I am getting this issue too, but like @mikeahirsch said it works if I switch to `npx tsc-alias@1.2.11`

Hello, can you provide me with a typical example of a project that fails because all tests pass. Thank you

**Comment by adam-coster** [comment]
@mikeahirsch @kangzeroo The place where the error is thrown is where the code is expected to find some quote characters `"'`. The regex being used to match import statements has been updated and now also included `\`` characters; do you have any import/require statements in your code that use backticks (`\``) instead of single/double quotes?

https://github.com/justkey007/tsc-alias/blob/a3ae38d39cb950b865f0dbe4833439f127fbe952/src/index.ts#L180

My best guess is that the reference line needs to be updated to include backticks, and that the new regex is allowing import statements that previously weren't being processed to now be processed.

Another option is to not allow backticks in import statement matches, which is a pretty common linter rule anyway.

**Comment by justkey007** [comment]
@adam-coster Even when I replace the code in [project3](https://github.com/justkey007/tsc-alias/blob/a3ae38d39cb950b865f0dbe4833439f127fbe952/projects/project3/src/index.ts) with this code using the backticks I don't see any errors.

```typescript
import { Controller } from '@controllers/index';

new Controller();

import(`@controllers/index`);

require(`@controllers/index`);

```

So @mikeahirsch  and @kangzeroo can quickly modify the code in node_module and do a `console.log(orig)` before this code here on line 112 from `node_modules/tsc-alias/dist/index.js`.

https://github.com/justkey007/tsc-alias/blob/a3ae38d39cb950b865f0dbe4833439f127fbe952/src/index.ts#L180
