### ISSUE TITLE
If I use `@username/tsconfig` extends, get `The JSON file is invalid` error

### ISSUE THREAD

**Issue by p-chan** [justkey007/tsc-alias#5]
I use shared tsconfig in my project. ( [@p-chan/tsconfig](https://www.npmjs.com/package/@p-chan/tsconfig) )
However, I'm having trouble using tsc-alias in conjunction with shared tsconfig and I'm getting an error.

If you know of a solution, I'd be happy to let you know.

---

```tsconfig.json
{
  "extends": "@p-chan/tsconfig",
  "compilerOptions": {
    "outDir": "./dist",
    "baseUrl": "./",
    "paths": {
      "@config/*": ["./src/config/*"],
      "@controllers/*": ["./src/controllers/*"],
      "@middlewares/*": ["./src/middlewares/*"]
    }
  }
}
```

```package.json
{
  ...
  "scripts": {
    "build": "tsc",
    "postbuild": "tsc-alias",
  },
  ...
}
```

```shell
$ npm run build

Error:  The JSON file is invalid ==> /Users/p-chan/src/github.com/p-chan/myproject/@p-chan/tsconfig
```

(`myproject` equal process.cwd().)

**Comment by justkey007** [comment]
Just use a relative path to the node_modules folder where your extended tsconfig is located

**Comment by p-chan** [comment]
`"extends": "./node_modules/@p-chan/tsconfig/tsconfig.json"` -> It's fixed! Thank you!

**Comment by mgcrea** [comment]
Just encountered this as well with `"extends": "@tsconfig/node14/tsconfig.json",` wouldn't it be better to automatically prefix with node_modules when extends starts with an `@`, should cover most use cases.

**Comment by justkey007** [comment]
> Just encountered this as well with `"extends": "@tsconfig/node14/tsconfig.json",` wouldn't it be better to automatically prefix with node_modules when extends starts with an `@`, should cover most use cases.

I took note. Thank you
