### ISSUE TITLE
Not finding @tsconfig packages in NPM7 workspace.

### ISSUE THREAD

**Issue by mctrafik** [justkey007/tsc-alias#55]
Running into this issue now:

```
12:05:03 Info: === tsc-alias starting ===
12:05:03  Error:  File $WORKSPACE/$REPO/packages/$SUB_PACKAGE/node_modules/@tsconfig/node14/tsconfig.json not found
```

Where it shouldn't be found because this package is part of a monorepo and all the packages are in the node_modules at the root, directory. I.e. `tsc-alias` should be looking at `$WORKSPACE/$REPO/node_modules/@tsconfig/node14/tsconfig.json`. I.e. it should be using the normal module resolution, recursively checking ancestor directory's `node_modules`.

More specifically, in the $SUB_PACKAGE we have the following:

tsconfig:
```json
{
  "extends": "@tsconfig/node14/tsconfig.json",
  "compilerOptions": {
     ...
  }
}
```

My guess is that this function (`resolveTsConfigExtendsPath`) needs to be updated to follow the regular node module resolution pattern.

**Comment by raouldeheer** [comment]
@mctrafik Do you have a public repo I could use for testing a fix?

**Comment by mctrafik** [comment]
I don't have a public repo. The files you'd need to set-up a repro:

Root: `/package.json`:

```
{
  "name": "root-package",
  "scripts": {
     "build": "npm run build -ws",
  },  
  "workspaces": [
    "./packages/*"
  ],
  ...
}
```

`/packages/packageA/package.json`:

```
{
  "name": "packageA",
  "scripts": {
     "build": "tsc && tsc-alias",
     ...
  },
 "dependencies": {
    "@tsconfig/node14": "^1.0.0",
    ...
  }
  ...
}
```

`/packages/packageB/package.json`:

```
{
  "name": "packageB",
  "dependencies": {
    "@tsconfig/node14": "^1.0.0",
    ...
  }
  ...
}
```

Now run `npm install && npm build` from root and it should install the entire workspace and build it and the build step fails.

**Comment by raouldeheer** [comment]
I've added the test project to the pull request.
The test is passing with the fix, so it should be fixed in the next release.
