### ISSUE TITLE
tsc-alias does not take custom tsconfig.json file 

### ISSUE THREAD

**Issue by Lazarencjusz** [justkey007/tsc-alias#62]
Hi,

like above, I run command `tsc-alias -p tsconfig.compile.json` and I get error `compilerOptions.paths is not set` which is not tru for above file, but it is true for default `tsconfig.json` file. So I put `paths` to default `tsconfig` and the error changed to missing `outDir` which again, is missing from `tsconfig.json` but exists in `tsconfig.compile.json`.

This bug exists from `@1.4`.

**Comment by clifflaschet** [comment]
I observed the same issue in `1.4.0`, when using a particular tsconfig file passed via the `-p` option. Not occurring in `1.3.10`.

**Comment by raouldeheer** [comment]
@Lazarencjusz @clifflaschet the issue of commander options being undefined has been fixed in pr #61. It will be fixed in the next release.

**Comment by KakakuCZ** [comment]
same here :(

**Comment by tusbar** [comment]
If you’re using `yarn`, you can define the following resolution in your `package.json`:

```json
"resolutions": {
  "tsc-alias/commander": "6.2.1"
},
```

Not sure how to do this with `npm`. :)

**Comment by raouldeheer** [comment]
@Lazarencjusz @tusbar @KakakuCZ @clifflaschet The 1.4.1 patch is now on npm. So this issue should be fixed.
