### ISSUE TITLE
[Feature] Support baseUrl without paths

### ISSUE THREAD

**Issue by haoadoresorange** [justkey007/tsc-alias#63]
As title said, should it work without any paths but only baseUrl ?

**Comment by raouldeheer** [comment]
Do you mean [this](https://github.com/justkey007/tsc-alias/discussions/27)?

**Comment by haoadoresorange** [comment]
hmm no I mean, currently tsc-alias work with `paths` field in `tsconfig`. But setting only `baseUrl` has similar effect, could it work with that only ?

**Comment by raouldeheer** [comment]
Right now it wouldn't work, because tsc-alias makes a list of all aliases and matches that with the imports. So when paths is empty there won't be any aliases to match so it won't find any results.

**Comment by haoadoresorange** [comment]
is that something viable ?

**Comment by justkey007** [comment]
@haoadoresorange 
How setting only baseUrl has a similar effect? Are you saying that without defining the paths option in tsconfig you can use aliases using only baseUrl?

**Comment by raouldeheer** [comment]
The requested behavior is that "index" will be replaced by "${baseurl}/index". Where index can be any path in the baseurl directory.

**Comment by raouldeheer** [comment]
I've got a prototype of this feature working; I'll improve it tomorrow. Haven't fully tested it yet so I'm not sure if it's a viable solution.

**Comment by justkey007** [comment]
@raouldeheer @haoadoresorange 
Thank you, the request was well understood

**Comment by ChrisChiasson** [comment]
@raouldeheer it seems like if we want `baseUrl="."`, so that absolute imports start with `src/` we would need `paths: {"src/*": "src/*"}` in tsconfig.json. I was able to figure this out by taking project 16 from PR #67 and changing `baseUrl` and all the `imports`.   I used project 10 for comparison. Thank you for your work on this project!
