### ISSUE TITLE
tsc-alias command line arguments are not parsed 

### ISSUE THREAD

**Issue by ChlorUpload** [justkey007/tsc-alias#65]
I found that `tsc-alias --watch` does not work and why this issue is happening.

In `src/bin/index.ts`, your code to parse command-line arguments seems good. But this change is not reflected in the `dist/bin/index.js` (current version is v1.4.0).

p.s. I think using `concurrently` would be stable.

(in package.json)
"build:watch": "concurrently  \\"tsc -w\\" \\"tsc-alias --watch\\""

**Comment by raouldeheer** [comment]
This is a known issue. fixed in #61.

https://github.com/justkey007/tsc-alias/issues/62#issuecomment-957924947
https://github.com/justkey007/tsc-alias/issues/48#issuecomment-955161443
https://github.com/justkey007/tsc-alias/discussions/64
