### ISSUE TITLE
Replaces require to npm module

### ISSUE THREAD

**Issue by she11sh0cked** [justkey007/tsc-alias#71]
Given the following typescript file...
```ts
// file: src/index.ts

import graphql from "graphql";

import typeDefs from "./graphql/typeDefs";

export { graphql, typeDefs };
```
with the following tsconfig...
```json5
// file: tsconfig.json

{
    "compilerOptions": {
        "baseUrl": "./src",
        "paths": {
            "~/*": ["*"]
        }
    }
}
```
tsc-alias modifies the imports like so:
```js
// file: src/index.js

"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.typeDefs = exports.graphql = void 0;
//!!! orig: const graphql_1 = __importDefault(require("graphql"));
const graphql_1 = __importDefault(require("./graphql"));
exports.graphql = graphql_1.default;
const typeDefs_1 = __importDefault(require("./graphql/typeDefs"));
exports.typeDefs = typeDefs_1.default;
//# sourceMappingURL=index.js.map
```

I guess the `require('graphql')` is modified because there is a folder called "graphql" in `src/` right? Is there a way to prevent paths to npm packages from being modified?

Here is a repo containing a jest test for this: https://github.com/she11sh0cked/tsc-alias-issue

**Comment by raouldeheer** [comment]
This problem is because of issue #63 
This shouldn't happen if the `graphql` directory doesn't have a index file.

**Comment by she11sh0cked** [comment]
The [graphql directory](https://github.com/she11sh0cked/tsc-alias-issue/tree/main/src/graphql) does in fact not have a index file.

**Comment by raouldeheer** [comment]
pr #72 should add the functionality to disable the BaseUrl replacer with a simple tsconfig option.

```jsonc
{
  "compilerOptions": {
    ...
  },
  "tsc-alias": {
    "replacers": {
      "BaseUrl": {
        "enabled": false
      }
    }
  }
}
```

**Comment by searleser97** [comment]
I don't think just disabling `baseUrl` replacements would be a proper solution, that means we can't use it without defining path aliases right? Could we instead add an option to ignore some folders in the outDir ? in this particular case it would be the "graphql" folder
