### ISSUE TITLE
Issue with relative folder imports such as `./something` for `./something/index.ts` when using `--resolve-full-paths`

### ISSUE THREAD

**Issue by nicholas-ochoa** [justkey007/tsc-alias#75]
I'm seeing a problem with relative folder imports that have an implied `index.js` when using `--resolve-full-paths`. I'm running `tsc-alias --resolve-full-paths` for each of these examples:

Before:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/126299/145614285-543582bd-d795-427a-a19c-b7831ed5fe04.png">

Actual Output:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/126299/145614341-2b4f376c-65b7-4e9d-a868-9a6390897a88.png">
(Note the lack of a leading `./` on the `authorization` and `test-helpers` imports)

Expected output:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/126299/145614450-871d95db-7257-4492-b5f1-e47449b5c673.png">

Here is what the directory structure looks like:
<img width="219" alt="image" src="https://user-images.githubusercontent.com/126299/145615218-740951b5-0fa5-49db-b251-3e3941bc0cc8.png">

`tsconfig.json`:
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "./dist",
    "rootDir": ".",
    "baseUrl": ".",
    "paths": {
      "@container": ["src/container.ts"],
      "@interfaces": ["src/interfaces.ts"],
      "@main": ["src/main.ts"],
      "@util": ["src/utils/index.ts"]
    }
  },
  "include": ["src/**/*.ts", "test/**/*.ts"]
}
```
I have tried changing `rootDir` and `baseUrl` to `./` instead of `.` but that didn't make a difference. 

As a workaround for now I was able to grab the latest copy of this package from git and build it to use the new replacer functionality. Using this replacer solved my issue, but ideally I think this should be built in to the package if possible:

```javascript
function testReplacer({ orig, file, config }) {
  const regex = /from '[a-z].*index.js'$/g;

  if (orig.match(regex)) {
    orig = orig.replace('from \'', 'from \'./');
  }

  return orig;
}

exports.default = testReplacer;
```

**Comment by raouldeheer** [comment]
@nicholas-ochoa Does pr #76 fix your issue?

**Comment by nicholas-ochoa** [comment]
@raouldeheer That seems to have fixed it perfectly. Thank you for the quick turnaround!
