### ISSUE TITLE
use with ts-node

### ISSUE THREAD

**Issue by eng-dibo** [justkey007/tsc-alias#81]
how to configure `tsc-alias` to be used with `ts-node`?
you may need to implement a register

```
node --experimental-modules --experimental-specifier-resolution=node -r tsc-alias/register --loader ts-node/esm ./tasks/index.ts
```

`tsconfig-paths` and `module-alias` don't work with module projects. i.e if you set `type: module` in your package .json

[minimal repo](https://stackblitz.com/edit/node-z4b52r?file=index.ts)
run `npm run start:paths`

**Comment by eng-dibo** [comment]
> tsc-alias has resolveFullPaths for module support.

that's why I want to depend on it on both compiletime (as it) and runtime (as suggested in this issue)

**Comment by eng-dibo** [comment]
any news?

**Comment by raouldeheer** [comment]
It will take a bit more time because tsc-alias needs files to resolve the aliases and tsc-alias was never designed for runtime use.

**Comment by ecker00** [comment]
Is this no longer planned as the issue was closed?

**Comment by justkey007** [comment]
@ecker00 tsc-alias was never designed for runtime use.
