### ISSUE TITLE
Bug: replace module names incorrectly (default import)

### ISSUE THREAD

**Issue by MohamadKh75** [justkey007/tsc-alias#82]
Hey

First of all, thanks for this awesome package 😁

We have a small bug.

## Steps

1. Import [`sharp`](https://github.com/lovell/sharp) with:

```ts
import sharp from 'sharp';

// ...
```

2. Run `"tsc && tsc-alias"`

## Expected

Compiled to JS:

```js
const sharp_1 = __importDefault(require('sharp'));
```

## Actual

Compiled to JS:

```js
const sharp_1 = __importDefault(require('../sharp'));
```

So there the bug is here! If I remove `tsc-alias`, I can run the project successfully (via `tsconfig-paths` for testing)

**Comment by raouldeheer** [comment]
@MohamadKh75 
This sounds like issue #71 
Is there a file in the upper directory called sharp?

**Comment by MohamadKh75** [comment]
Thanks for your flashy quick response ❤️

Yep, and I fixed it with:

```json
{
  "compilerOptions": {
    ...
  },
  "tsc-alias": {
    "replacers": {
      "BaseUrl": { enabled": false }
    }
  }
}
```

**Comment by MohamadKh75** [comment]
Hey!

I guess https://github.com/justkey007/tsc-alias/pull/94 has made a regression cause I get this exact error even with:

```json
{
  "compilerOptions": {},
  "tsc-alias": {
    "replacers": {
      "BaseUrl": { "enabled": false }
    }
  }
}
```

cc @raouldeheer

**Comment by raouldeheer** [comment]
@MohamadKh75 The name of baseurl has been changed to `baseurl` in the `1.6.2` release.

**Comment by MohamadKh75** [comment]
> @MohamadKh75 The name of baseurl has been changed to `baseurl` in the `1.6.2` release.

Well, I guess that should be a breaking change then 😁
