### ISSUE TITLE
Some import paths aren't replaced

### ISSUE THREAD

**Issue by kraftwerk28** [justkey007/tsc-alias#83]
Here's a reproduction repl:
https://replit.com/@kraftwerk28/IntrepidMediumblueOffice#tsconfig.json

Files worth to look at are `tsconfig.json`, `index.ts` and `build/index.js`. 2nd and 3rd imports generated in `build/index.js` aren't replaced by `tsc-alias`. I believe the tool doesn't work well with `$` and with `foo/*.bar` (where there's a trailing path after the glob).

**Comment by raouldeheer** [comment]
@kraftwerk28 Thank you for opening this issue.
`$` doesn't working because `$` is a regex anchor.
Trailing path after the `*` doesn't work because `tsc-alias` expects the `*` to be the last char of an alias.

**Comment by raouldeheer** [comment]
@sinbino #91 should fix that
