### ISSUE TITLE
Ability to run for a single file, and return the modified content as a string

### ISSUE THREAD

**Issue by eturino** [justkey007/tsc-alias#84]
That way we could use tsc-alias as a custom jest transformer.

**Comment by raouldeheer** [comment]
@eturino 
I'll look into it. Should that be available as an exported function?

**Comment by eturino** [comment]
I'm preparing a PR for it @raouldeheer

**Comment by eturino** [comment]
@raouldeheer PR with tests and the rest #85

**Comment by eturino** [comment]
Thanks a lot @justkey007. Could I ask you to make a release? 😊

**Comment by justkey007** [comment]
Yes I will soon. Thank you
