### ISSUE TITLE
Urgent help needed - Failed to import `replacer` file

### ISSUE THREAD

**Issue by dittmarconsulting** [justkey007/tsc-alias#95]
Hi there,

I've been trying to use this package successfully but I can't import the replacer file.

Here is my file structure

```
mono-repo
- packages
- - project
- - - src
- - - - assets
- - - - component
- - - - - Button
- - pathReplacer.js
- - tsconfig.json
tsconfig.json
```

In the Button file, I use an alias for the path like `require('#/assets/images/button.png')`

Here is my project `tsconfig.json`

```json
{
  "extends": "../../tsconfig.json",
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "dist"],
  "compilerOptions": {
    "skipLibCheck": true,
    "emitDecoratorMetadata": true,
    "outDir": "dist",
    "isolatedModules": true,
    "declarationDir": "dist",
    "typeRoots": ["./src/types/types.d.ts", "./src/types/styled.d.ts", "../../node_modules/@types"],
    "paths": {
      "#*": ["./src/*"]
    }
  },
  "references": [
    {
      "path": "../ui-core"
    }
  ],
  "tsc-alias": {
    "verbose": false,
    "resolveFullPaths": true,
    "replacers": {
      "pathReplacer": {
        "enabled": true,
        "file": "./pathReplacer.js"
      }
    }
  }
}
```
I can build the project fine with `tsc` without errors but as soon I add the `tsc-alias` section in the `tsconfig.json` file I get this error

```
tsc-alias error: Failed to import replacer "./pathReplacer.js"
```

Here the content of `pathReplacer.js`

```js
import { replaceTscAliasPaths } from 'tsc-alias'

replaceTscAliasPaths()
```

Can you help me to resolve this problem?

**Comment by justkey007** [comment]
Hello, you need to move the "pathReplacer.js" file to the root of your project. That is, in the folder (`process.cwd()`) from which you launch tsc-alias.

Like this:
mono-repo
- packages
- - project
- - - src
- - - - assets
- - - - component
- - - - - Button
- - tsconfig.json
tsconfig.json
pathReplacer.js

**Comment by dittmarconsulting** [comment]
Hi @justkey007,

Thank you for your fast reply. Much appreciated.

Let's rename the mono-repo and the project to something meaningful like `bestapp` and `ui-components`. So the folder structure would look like that now

```
bestapp
- packages
- - ui-components
- - - ...
- - - pathReplacer.js
- - - tsconfig.json
- - - package.json
tsconfig.json
package.json
```

The `package.json` file of `ui-components` project I would look like that:

```json
{
  "name": "@bestapp/ui-components",
  "private": true,
  "scripts": {
    "build:library": "tsc && tsc-alias"
  },
  ...
}
```

and I would invoke the `build:library` command from the mono-repo root like that

```
yarn workspace @bestapp/ui-components build:library
```

So, the `pathReplacer.js` has to be in the `ui-components` folder, right?

**Comment by dittmarconsulting** [comment]
OK, I'm a step further with the investigation.

I actually print out the catch errors for:

```js
if ((0, fs_1.existsSync)(path)) {
  try {
    yield tryImportReplacer(path);
    continue;
  } catch (_c) { 
    console.log('error', _c) // <------- added the log on line 94
  }
}
for (const targetPath of node_modules.map((v) => (0, path_1.join)(dir, v, file))) {
  try {
    yield tryImportReplacer(targetPath);
    continue;
  } catch (_d) { 
    console.log('error', _d) // <------- added the log on line 103
  }
}
```

in file `node_modules/tsc-alias/dist/helpers/replacers.js`

And got this error 

```
import { replaceTscAliasPaths } from 'tsc-alias'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Then I changed the import of the `pathReplacer.js` like that

```js
const { replaceTscAliasPaths } = require('tsc-alias')

replaceTscAliasPaths()
```

But now I get this error

```
yarn workspace @ampjar/ui-components build:library                                                                                                                   1 ↵
yarn workspace v1.22.17
yarn run v1.22.17
$ tsc && tsc-alias
tsc-alias info: Added replacer "pathReplacer.js"
/node_modules/tsc-alias/dist/helpers/replacers.js:134
        code = (0, utils_1.replaceSourceImportPaths)(code, file, (orig) => replacer({
                                                                           ^

TypeError: replacer is not a function
```

**Comment by dittmarconsulting** [comment]
I know you closed this issue @justkey007 

But I also logged out how the `replacer` object looks like (line 71)

```js
const replacer = entries_1_1.value;
console.log('replacer', replacer)
```

```
replacer [ 'default', { enabled: true } ]
replacer [ 'BaseUrl', { enabled: true } ]
replacer [ 'pathReplacer', { enabled: true, file: 'pathReplacer.js' } ]
```

**Comment by justkey007** [comment]
> Hi @justkey007,
> 
> Thank you for your fast reply. Much appreciated.
> 
> Let's rename the mono-repo and the project to something meaningful like `bestapp` and `ui-components`. So the folder structure would look like that now
> 
> ```
> bestapp
> - packages
> - - ui-components
> - - - ...
> - - - pathReplacer.js
> - - - tsconfig.json
> - - - package.json
> tsconfig.json
> package.json
> ```
> 
> The `package.json` file of `ui-components` project I would look like that:
> 
> ```json
> {
>   "name": "@bestapp/ui-components",
>   "private": true,
>   "scripts": {
>     "build:library": "tsc && tsc-alias"
>   },
>   ...
> }
> ```
> 
> and I would invoke the `build:library` command from the mono-repo root like that
> 
> ```
> yarn workspace @bestapp/ui-components build:library
> ```
> 
> So, the `pathReplacer.js` has to be in the `ui-components` folder, right?

Please specify the tsconfig in which the replacer parameters are located as here.
https://github.com/justkey007/tsc-alias/blob/68e0083dc6f812498f92ef2e2f3969d073ec05b9/projects/project20/package.json

**Comment by justkey007** [comment]
Please specify the tsconfig in which the replacer parameters are located as here. And don't forget to use the new 1.6.2

https://github.com/justkey007/tsc-alias/blob/68e0083dc6f812498f92ef2e2f3969d073ec05b9/projects/project20/package.json#L1-L9

**Comment by dittmarconsulting** [comment]
The only command that worked was this one

```
"scripts": {
    "build:library": "tsc -p tsconfig.json && tsc-alias -p tsconfig.json",
},
```

But now I get this error

```
tsc-alias error: Failed to import replacer "/<user path>/react-native/bestapp/packages/ui-components/pathReplacer.js", not in replacer format.
```

**Comment by justkey007** [comment]
What is the content of this file "/<user path>/react-native/bestapp/packages/ui-components/pathReplacer.js" ?

**Comment by dittmarconsulting** [comment]
Just like that

```js
const { replaceTscAliasPaths } = require('tsc-alias')

replaceTscAliasPaths()
```

I don't know if I have to give `option` since I suspect that the alias comes from the `tsconfig.json` file.

**Comment by justkey007** [comment]
> The only command that worked was this one
> 
> ```
> "scripts": {
>     "build:library": "tsc -p tsconfig.json && tsc-alias -p tsconfig.json",
> },
> ```
I specify that the default tsconfig is the one located at the location from which you launch the `tsc-alias` command

**Comment by dittmarconsulting** [comment]
Yes.

Here the content

```json
{
  "extends": "../../tsconfig.json",
  "include": ["**/*.ts", "**/*.tsx", "**/*.js"],
  "exclude": ["node_modules", "dist"],
  "compilerOptions": {
    "skipLibCheck": true,
    "emitDecoratorMetadata": true,
    "outDir": "dist",
    "isolatedModules": true,
    "declarationDir": "dist",
    "typeRoots": ["./src/types/types.d.ts", "./src/types/styled.d.ts", "../../node_modules/@types"],
    "paths": {
      "#*": ["./packages/ui-components/src/*"]
    }
  },
  "references": [
    {
      "path": "../ui-core"
    }
  ],
  "tsc-alias": {
    "verbose": true,
    "resolveFullPaths": true,
    "replacers": {
      "pathReplacer": {
        "enabled": true,
        "file": "pathReplacer.js"
      }
    }
  }
}
```

**Comment by justkey007** [comment]
> Just like that
> 
> ```js
> const { replaceTscAliasPaths } = require('tsc-alias')
> 
> replaceTscAliasPaths()
> ```

This is not the right content, please take inspiration from [Project 20](https://github.com/justkey007/tsc-alias/tree/68e0083dc6f812498f92ef2e2f3969d073ec05b9/projects/project20)

**Comment by dittmarconsulting** [comment]
I see. That was not clear from the docs.

I tried that 

```js
exports.default = ({ orig, file, config }) => {
  return orig;
};
```

No errors but all paths are still the same

**Comment by dittmarconsulting** [comment]
Sorry, my bad. I can see that the import paths now have changed.

AWSOME @justkey007

That's amazing. 

If for instance an `Image` has a `require('#/assets/images/access-camera-roll.png')` like that. That is untouched and I only looked at that.

**Comment by justkey007** [comment]
> If for instance an `Image` has a `require('#/assets/images/access-camera-roll.png')` like that. That is untouched and I only looked at that.

This is where your `pathReplacer.js` file will play its part if you put the right code in it.

**Comment by dittmarconsulting** [comment]
Awesome. 

Thank you so much for your help. 

I only looked at the https://github.com/justkey007/tsc-alias#usage section and thought I have to write the `replacer` like that.

WELL DONE !!!
